# Generated by Django 4.2 on 2023-04-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20230327_2033"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("UAH", "UAH"), ("USD", "USD"), ("EUR", "EUR")],
                default="UAH",
                max_length=16,
            ),
        ),
    ]
