# Generated by Django 4.2 on 2023-05-11 16:50

from django.db import migrations
from django.utils.text import slugify


def up(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    for category in Category.objects.iterator():
        category.slug = slugify(category.name)
        category.save(update_fields=('slug',))


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_category_is_manual_slug_category_slug"),
    ]

    operations = [
        migrations.RunPython(up, reverse_code=migrations.RunPython.noop)
    ]
